
		<?php $this->partial("common/header"); ?>
<script type="text/javascript" src="/js/page.js"></script>
<script src="/js/modal/bootstrap.js"></script>
<script type="text/javascript" src="/js/zclip/jquery.zclip.js"></script>
<link href="/css/modal/bootstrap.css" rel="stylesheet" />
<script src="/js/form.js"></script>
<script type="text/javascript" src="/js/layer/layer.min.js"></script>
		<link rel="stylesheet" type="text/css" href="/js/layer/skin/layer.css">
<script type="text/javascript" src="/js/pickerDateRange/dateRange.js"></script>
<link rel="stylesheet" type="text/css"
	href="/js/pickerDateRange/dateRange.css" />
	<div class="main_box">
<?php $this->partial("common/headernav"); ?>
					<div class="right main">
					<div class="com_tab_box clearfix">
					<ul class="left">
						<li ><a href="<?php echo $this->url->get('static/gueststatic');?>">数据统计</a></li>
						<li>|<a href="<?php echo $this->url->get('agentguests/platformstatistics',array('type'=>1));?>">渠道统计</a></li>
					</ul>
					</div>
			<div class="container">
			<form>
				<div class="mt20">
					
									<div class="ta_date" id="div_date_demo3">
										<span class="date_title" id="date_demo3"></span> <input
											type="hidden"
											value='<?php echo $this->request->getQuery('startDate');?>'
											name="startDate"> <input type="hidden"
											value='<?php echo $this->request->getQuery('endDate');?>'
											name="endDate"> <a class="opt_sel" id="input_trigger_demo3"
											href="#"> <i class="i_orderd"></i>
										</a>
									</div>&nbsp;&nbsp;
					渠道类型 ： <select class="com_select w_100" name="type">
										<?php
foreach($data['PlatformType'] as $key => $val)
										{
											if($this->request->getQuery('type') == $key)
											{
												echo "<option value={$key} selected='selected'>{$val}</option>";
											}
											else
											{
												echo "<option value={$key}>{$val}</option>";
											}
										}
										?>
								</select>
					</select>&nbsp;&nbsp;
					名称 ： <input class="com_input w_60" name="name" value="<?php echo $this->request->getQuery("name");?>"/>
  <input type="submit" class="search_btn com_search_btn ml20" value="搜 索" />
				</div>
</form>
				<table class="domain_table mt20 clearfix" width="100%">
					<colgroup>
						<col width="3%"/>
						<col width="25%"/>
						<col width="20%"/>
						<col width="15%"/>
						<col/>
					</colgroup>
					<thead>
						<tr>
							<th></th>
							<th>名称</th>
							<th>所属渠道</th>
							<th style="text-align:center;">点击量</th>
						</tr>
					</thead>
					<tbody>
														<?php
														if(! empty($data['list']))
														{
															$str='';
															foreach($data['list'] as $val)
															{
																
																$str .= '<tr><td></td>';
																$str .= "<td>{$val['PlatformName']}</td>";
																$str .= "<td>{$val['PlatformTypeCn']}</td>";
																$str .= "<td class=center>{$val['ClickNum']}</td>";
															}
															echo $str;
														}
														else{
                                    echo '<tr><td colspan="10" style=" text-align: center;">无查询结果</td></tr>';
														}
														?>

					</tbody>
				</table>
					<div class="right">
<?php echo $data['page'];?>
					</div>
			</div>
		</div>
		</div>
	</div>
	<script>
	var url='<?php echo $this->url->get('agentguests/platformstatistics',array('type'=>1));?>';
	var top_url='<?php echo $this->url->get('Agentguests/domainAgent');?>';
	var left_url='<?php echo $this->url->get('static/gueststatic');?>';
navLight(url,left_url,top_url);
var today = getDays(0);
var lasr7Days=getDays(-7);
var defaultStartDate='<?php echo $this->request->getQuery('startDate');?>'?'<?php echo $this->request->getQuery('startDate');?>':today;
var defaultendDate='<?php echo $this->request->getQuery('endDate');?>'?'<?php echo $this->request->getQuery('endDate');?>':today;
	var dateRange = new pickerDateRange('date_demo3', {
		aRecent7Days : 'aRecent7DaysDemo3', //最近7天
		isTodayValid : true,
		startDate : defaultStartDate,
		endDate : defaultendDate,
		//needCompare : true,
		//isSingleDay : true,
		//shortOpr : true,
		defaultText : ' 至 ',
		inputTrigger : 'input_trigger_demo3',
		theme : 'ta',
		success : function(obj) {
			$("#dCon_demo3").html('开始时间 : ' + obj.startDate + '<br/>结束时间 : ' + obj.endDate);
			$('input[name="startDate"]').val(obj.startDate);
			$('input[name="endDate"]').val(obj.endDate);
		}
	});
		function getDays(AddDayCount){

		var dd = new Date(); 
		dd.setDate(dd.getDate()+AddDayCount);//获取AddDayCount天后的日期 
		var y = dd.getFullYear(); 
		var m = (dd.getMonth()+1)<10?"0"+(dd.getMonth()+1):(dd.getMonth()+1);//获取当前月份的日期，不足10补0
		var d = dd.getDate()<10?"0"+dd.getDate():dd.getDate(); //获取当前几号，不足10补0
		return y+"-"+m+"-"+d; 
		}
</script>
<?php $this->partial("common/footer"); ?>