<?php $this->partial("common/header"); ?>
<script type="text/javascript" src="/js/page.js"></script>
<script src="/js/modal/bootstrap.js"></script>
<script type="text/javascript" src="/js/zclip/jquery.zclip.js"></script>
<link href="/css/modal/bootstrap.css" rel="stylesheet" />
<script src="/js/form.js"></script>
<script type="text/javascript" src="/js/layer/layer.min.js"></script>
<link rel="stylesheet" type="text/css" href="/js/layer/skin/layer.css">
<script type="text/javascript" src="/js/pickerDateRange/dateRange.js"></script>
<link rel="stylesheet" type="text/css"
	href="/js/pickerDateRange/dateRange.css" />
<div class="main_box">
<?php $this->partial("common/headernav"); ?>
		<div class="right main">
<?php $this->partial("agentguests/spreadcommon"); ?>
			<div class="container">
			<form action='' id='spreaddoamin' name='spreaddoamin'>
				<div class="com_search_box">
					<table>
						<colgroup>
							<col width="270" />
							<col width="220" />
							<col />
						</colgroup>
						<tbody>
							<tr>
								<td>
									<div class="ta_date" id="div_date_demo3">
										<span class="date_title" id="date_demo3"></span> <input
											type="hidden"
											value='<?php echo $this->request->getQuery('startDate');?>'
											name="startDate"> <input type="hidden"
											value='<?php echo $this->request->getQuery('endDate');?>'
											name="endDate"> <a class="opt_sel" id="input_trigger_demo3"
											href="#"> <i class="i_orderd"></i>
										</a>
									</div>
								</td>
								<td colspan="2">域 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名： <input
									type="text" class="com_input w_80" name="DomainName"
									value="<?php echo $this->request->getQuery('DomainName');?>" />
								</td>
								<td>推广渠道 ： <select class="com_select w_100" name="PlatformType">
										<option value="">全部</option>
										<?php
										foreach($data['PlatformType'] as $key => $val)
										{
											if($this->request->getQuery('PlatformType') == $key)
											{
												echo "<option value={$key} selected='selected'>{$val}</option>";
											}
											else
											{
												echo "<option value={$key}>{$val}</option>";
											}
										}
										?>
								</select>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="center mt20 mb20">
					<input class="com_search_btn search_btn" type="button" value="搜 索"
						onclick="check_spreaddoamin();" /> <input
						class="com_search_btn ml10" type="button" value="重 置"
						onclick="searchFormReset(this.form);" />
						<input type="hidden" value='<?php echo intval($this->request->getQuery('topic'));?>' name='topic'>
				</div>
			</form>
			<div>
				<div id="form-content" class="modal hide fade in ie"
					style="display: none;">

					<div class="pop_main">
						<div class="pop_hd">
							<a title="关闭" href="#" class="pop_close" data-dismiss="modal">x</a>
							<h3>获取代码</h3>
						</div>
						<div class="pop_bd border_gray">
							<div class="pop_top"></div>
							<div class="center mb20">
								<textarea class="pop_area adData copy"></textarea>
							</div>
						</div>

						<div class="com_btn_box mb30 mt20">
							<input type="button" value="关 闭" class="com_btn"
								data-dismiss="modal" />
						</div>
					</div>
				</div>
				<table class="domain_table clearfix" width="100%">
					<colgroup>
						<col width="25%" />
						<col width="25%" />
						<col width="25%" />
						<col width="25%" />
					</colgroup>
					<thead>
						<tr>
							<th>域名</th>
							<th><a
								href="<?php echo $this->url->get('Agentguests/spreaddomain',array_merge($this->request->getQuery(),array('sort'=>'price-'.$data['order']['priceSort'])));?>"> 当前价格 <?php echo $data['order']['priceSymbol'];?></a></th>
							<th><a
								href="<?php echo $this->url->get('Agentguests/spreaddomain',array_merge($this->request->getQuery(),array('sort'=>'percent-'.$data['order']['commissionSort'])));?>"> 佣金比例 <?php echo $data['order']['commissionSymbol'];?></a></th>
							<th>状态<i class="have_problem" style=" margin-top: -2px;" title="此状态为该域名的推广状态"></i></th>
						</tr>
					</thead>
					<tbody>
														<?php
														if(! empty($data['list']))
														{
															$str = '';
															foreach($data['list'] as $k => $val)
															{
																$str .= "<tr><td><a href=javascript:void(0) onclick=getDetail('{$val['DomainName']}',{$val['AgentDRId']}) >{$val['DomainName']}</a></td>";
																if(!$val['DomainInfo'])
																{
																	$str .= "<td>-</td>";
																	$str .= "<td>-</td>";
																}
																else
																{
																	$str .= "<td>" . round($val['DomainInfo']->Price, 2) . "元</td>";
																	$str .= "<td>".round($val['DomainInfo']->Percent, 2)."%</td>";
																}
																$str .= "<td>{$val['StatusCn']}</td></tr>";
																$str .= '<tr style="display:none;background-color: #f3f3f5;"id="detailArea' .
																	 $val['AgentDRId'] . '" class=detailData></tr>';
															}
															echo $str;
														}
														else
														{
															echo '<tr><td colspan="10" style=" text-align: center;">无查询结果</td></tr>';
														}
														?>
						</tbody>
				</table>
			</div>
			<div class="page_box clearfix">
				<div class="right">
<?php echo $data['page'];?>
					</div>
			</div>
		</div>
	</div>
</div>
<script>
	var today = getDays(0);
	var lasr7Days=getDays(-7);
	var defaultStartDate='<?php echo $this->request->getQuery('startDate');?>'?'<?php echo $this->request->getQuery('startDate');?>':today;
	var defaultendDate='<?php echo $this->request->getQuery('endDate');?>'?'<?php echo $this->request->getQuery('endDate');?>':today;
		var dateRange = new pickerDateRange('date_demo3', {
			aRecent7Days : 'aRecent7DaysDemo3', //最近7天
			isTodayValid : true,
			startDate : defaultStartDate,
			endDate : defaultendDate,
			//needCompare : true,
			//isSingleDay : true,
			//shortOpr : true,
			defaultText : ' 至 ',
			inputTrigger : 'input_trigger_demo3',
			theme : 'ta',
			success : function(obj) {
				$("#dCon_demo3").html('开始时间 : ' + obj.startDate + '<br/>结束时间 : ' + obj.endDate);
				$('input[name="startDate"]').val(obj.startDate);
				$('input[name="endDate"]').val(obj.endDate);
			}
		});
			function getDays(AddDayCount){

			var dd = new Date(); 
			dd.setDate(dd.getDate()+AddDayCount);//获取AddDayCount天后的日期 
			var y = dd.getFullYear(); 
			var m = (dd.getMonth()+1)<10?"0"+(dd.getMonth()+1):(dd.getMonth()+1);//获取当前月份的日期，不足10补0
			var d = dd.getDate()<10?"0"+dd.getDate():dd.getDate(); //获取当前几号，不足10补0
			return y+"-"+m+"-"+d; 
			}
	var url='<?php echo $this->url->get('agentguests/spreaddomain',array('topic'=>intval($this->request->getQuery('topic'))));?>';
	var top_url='<?php echo $this->url->get('agentguests/domainagent');?>';
	var left_url='<?php echo $this->url->get('agentguests/spreaddomain',array('topic'=>0));?>';
	navLight(url,left_url,top_url);
</script>
<script>
function getDetail(Name,id){
		if($('#detailArea'+id).is(":hidden")){
	     $.ajax({
	         type: "POST",
	     url: "<?php echo $this->url->get('agentguests/spreadDetail');?>",
	     data: {'topic':<?php echo intval($this->request->getQuery('topic'));?>,'startDate':'<?php echo $this->request->getQuery('startDate');?>','endDate':'<?php echo $this->request->getQuery('endDate');?>','StartCommission':'<?php echo $this->request->getQuery('StartCommission');?>','EndCommission':'<?php echo $this->request->getQuery('EndCommission');?>','Name':Name,'sort':'<?php echo $this->request->getQuery('sort');?>','status':'<?php echo $this->request->getQuery('status');?>','agentType':1,'PlatformType':'<?php echo $this->request->getQuery('PlatformType');?>'},
	     beforeSend : function(){
	    },
	             success: function(data){
		             if(data!=''&&data!=null&&data!=undefined){
		     			var html='<td colspan="4"><table class="xiangqing_tab" width="100%"><colgroup><col width="15%"/><col width="25%"/><col width="25%"/><col width="20%"/><col/></colgroup><thead><tr><th>日期</th><th style="text-align:center;">点击量</th><th>渠道</th><th>推广码<i class="have_problem" title="蓝色为有效连接，可以复制；灰色为无效链接，无法复制" style=" margin-top: -2px;"></i></th><th>推广结果</th></tr></thead><tbody>';
						for ( var key in data) {
							html +="<tr><td>"+data[key]['CreateTime']+"</td>";
							html +="<td class=center>"+data[key]['ClickNum']+"</td>";
							html +="<td>"+data[key]['PlatformName']+"</td>";
							if(data[key]['Status']==1){
								
							html +="<td><a href=javascript:void(0) class=look tag='"+data[key]['Code']+"'>查看代码</a></td>";
							}else{
								html +="<td><span href=javascript:void(0) style='color:#ccc'>查看代码</span></td>";
								}
							if(data[key]['IsOrder']==1){
								
								html +="<td>成功</td></tr>";
								}else{
									html +="<td>继续努力</td></tr>";
									}
						}
						//copy('1111');
						//foreach($data['list'][$k]->Details as $v)
						//{
						//$str .= "<tr><td>{$v['CreateTime']}</td>";
						//$str .= "<td class=center>{$v['ClickNum']}</td>";
						//$str .= "<td>{$v['PlatformName']}</td>";
						//$str .= "<td><a href=>复制代码</a></td></tr>";
                       // }
html+='</tbody></table></td>';  
$('#detailArea'+id).html(html);
		             }     
	             },
	     error: function(){
	     layer.msg("系统繁忙",{icon: 5});
	     }
	           });
	     $('#detailArea'+id).show();
	    $('.detailData').not('#detailArea'+id).hide();
		}
	else{
		$('#detailArea'+id).hide();
		}
	}
	//$(document).on('click',".copy",function(){
		//copy('11');
			//});
				 function copy(data){
					    $(".copy").zclip({
							path: "/js/zclip/ZeroClipboard.swf",
							copy: function(){
							return data;
							},
							beforeCopy:function(){/* 按住鼠标时的操作 */
								$(this).css("color","orange");
							},
							afterCopy:function(){/* 复制成功后的操作 */
								$('.pop_top').html('<span class="success_top">代码复制成功</span>');
								//$(".copy-tips").fadeOut(3000);
					        }
						});
				 }
				$(document).on('click',".look",function(){
					$(".copy").text($(this).attr('tag'));
					$('.pop_top').html('');
					$('#form-content').modal({backdrop: 'static', keyboard: false}); 
	                   setTimeout(function(){
					$('.copy').trigger('click');
	                   },200);
					});
			$('.copy').click(function(){
				copy($(this).text());
				})




</script>
<?php $this->partial("common/footer"); ?>