<?php
use lib\agent\AgentManagerLib;
use core\Config;
$this->partial('common/header');
?>
<div class="main_box">
	<?php $this->partial('common/headernav');?>
	<div class="right main">
		<div class="com_tab_box">
			<ul class="clearfix">
				<li class="active"><a href="#">发域名</a></li>
				<li>|<a href="<?php echo $this->url->get('seller/shop');?>">发店铺</a></li>
			</ul>
		</div>
		<div class="container">
		<?php $this->partial('seller/searchForm');?>
			<div>
				<ul class="domain_tab_ul clearfix">
					<li><a href="<?php echo $this->url->get('seller/search');?>">所有域名</a></li>
					<li><a href="<?php echo $this->url->get('seller/unseted');?>">未设置</a></li>
					<li><a class="cur" href="#">已设置</a></li>
					<li><a href="<?php echo $this->url->get('seller/sold');?>">已售出</a></li>
				</ul>
				<table class="domain_table clearfix" width="100%">
					<colgroup>
						<col width="3%" />
						<col />
						<col width="12%" />
						<col width="12%" />
						<col width="13%" />
						<col width="15%" />
						<col width="25%" />
					</colgroup>
					<thead>
						<tr>
							<th><input type="checkbox" class="all_checked"
								onclick="allChecked(this)" /></th>
							<th>域名</th>
							<th><a
								href="<?php echo $this->url->get('seller/agented', array_merge($this->request->getQuery(), array('sort' => 'price-'.$order['priceSort'])));?>">当前价格 <?php echo $order['priceSymbol'];?></a></th>
							<th>类型</th>
							<th><a
								href="<?php echo $this->url->get('seller/agented', array_merge($this->request->getQuery(), array('sort' => 'finishtime-'.$order['finishTimeSort'])));?>">
									剩余时间 <?php echo $order['finishTimeSymbol'];?></a></th>
							<th><a
								href="<?php echo $this->url->get('seller/agented', array_merge($this->request->getQuery(), array('sort' => 'percent-'.$order['commissionSort'])));?>">
									佣金比例 <?php echo $order['commissionSymbol'];?></a></th>
							<th>&nbsp;操作</th>
						</tr>
					</thead>
					<tbody>
					<?php
					if(! $isEmpty)
					{
						foreach($domainList as $domain)
						{
							?>
						<tr>
							<td><input type="checkbox"
								value="<?php echo $domain->DomainAgentId;?>" name="domain"
								class="select_domain" onclick="isAllChecked();"
								<?php echo $domain->CreateTime > time() - Config::item('edittime')?'':'disabled';?> /></td>
							<td><a
								href="<?php echo $this->url->get('seller/detail/'.$domain->DomainName.'/'.$domain->DomainAgentId)?>"><?php echo $domain->DomainName;if($domain->Topic == 8):echo '&nbsp;<img src="../images/ico_03.png" alt="拍卖会" title="拍卖会" />';endif;?></a></td>
							<td><?php echo round($domain->Price, 2).'元';?></td>
							<td><?php if($domain->TransType == 1) echo '竞价'; elseif($domain->TransType == 4) echo '一口价';?></td>
							<td><?php $lib = new AgentManagerLib();echo $lib->newTimeToDHIS($domain->FinishTime);?></td>
							<td><?php echo round($domain->Percent, 2).'%';?></td>
							<td class="caozuo"><?php if($domain->CreateTime > time() - Config::item('edittime')):?>
								<a href="javascript:void(0);"
								onclick="inputScale(this, <?php echo $domain->DomainAgentId;?>, '<?php echo $this->url->get('seller/edit');?>', true)"
								class="edit_scale">修改</a>|<a href="javascript:void(0);"
								onclick="deletePercent(this, <?php echo $domain->DomainAgentId;?>);return false;">删除</a>
								<span class="clock_box"><img alt="倒计时" src="../images/clock.png"
									width="18px;" style="margin-top: -2px; margin-left: 5px;"
									title="倒计时" class="clock" /><em style="display: none;"></em></span><?php else:echo '&nbsp;-';endif;?>
							</td>
						</tr>
				<?php
						}
					}
					else
					{
						?>
						<tr>
							<td colspan="7" style="text-align: center;">无查询结果</td>
						</tr>
					<?php
					}
					?>
					</tbody>
				</table>
			</div>
			<?php if(!$isEmpty):?>
			<div class="page_box clearfix">
				<div class="left">
					<input class="com_btn" type="button" value="批量修改"
						onclick="multiSetAgent(this, '<?php echo $this->url->get('seller/edit');?>');" />
					<input class="com_btn" type="button" value="批量删除"
						onclick="deletePercent(this);" />
				</div>
				<div class="right"><?php echo $pageLink;?></div>
			</div>
			<div class="com_note mt20 mb20 clearfix">
				<h3 class="com_note_tit">注意事项：</h3>
				<ul class="com_note_list mt15">
					<li>设置成功的域名，将在30分钟后生效并进入米市，生效之后佣金比例将无法进行修改和删除，直到域名下架。</li>
				</ul>
			</div>
		<?php endif;?>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function(){
	navLight("<?php echo $this->url->get('seller/agented');?>", "<?php echo $this->url->get('seller/search');?>", "<?php echo $this->url->get('seller/search');?>");
});	

function timeFormat(time) {
	if(time <= 0)
	{
		return 'Timeout';
	}
	var leftTime = '';
	var nI = parseInt((time / 60) % 60);
	var nS = parseInt((time % 60));
	leftTime += nI? nI + '分': '';
	leftTime += nS? nS + '秒': '';
		
	return leftTime;
}

$('.clock').click(function() {
	var that = this;
	var id = $(this).parent().parent().parent().find('.select_domain').val();
	if(id == '' || id == undefined || id == 0 ) {
		return false;
	}
	$.ajax({
		url: "<?php echo $this->url->get('seller/update');?>",
		data: {'id' : id},
		dataType: "JSON",
		type: 'POST',
		success: function(data) {
			if(data.status == true) {
				$(that).next().html(timeFormat(data.leftTime));
				$(that).next().show();
				(function (){
					var timered = 0;
					setTimeout(function(){
						data.leftTime = data.leftTime-1;
						$(that).next().html(timeFormat(data.leftTime));
						timered++;
						console.log(timered);
						timered < 3 && data.leftTime >0 ? setTimeout(arguments.callee,1000) : '';
						},1000)
					})();
				setTimeout(function(){
					$(that).next().hide();
				}, 4000);
			} else {
				layer.msg('系统繁忙，请稍后再试',{icon: 2});
			}
		}
	});
});

function deletePercent(obj)
{
	var checkObj = $('.select_domain');
	var ids = [];

	for(var i=0;i<checkObj.length;i++)
	{
		if(!checkObj[i].checked || checkObj[i].disabled == 'disabled')
		{
			continue;
		}
		ids.push(checkObj[i].value);
	}
	
	domainAgentId = arguments[1]? arguments[1]: ids;

	
	if(confirm('确定要删除已设置好的佣金比例吗？'))
	{
		$.ajax({
			url: "<?php echo $this->url->get('seller/delete');?>",
			datatype: 'json',
			type: 'post',
			data: {'domainAgentId' : domainAgentId},
			success: function(data){
				if(data.flag == 3) {
					var oldLimit = parseInt(getUrlParam("limit_start"));
					var newLimit = parseInt(getUrlParam("limit_start")) - <?php echo \core\Config::item('pagesize');?>;
					var oldStr = "limit_start=" + oldLimit;
					var newStr = oldLimit ? "limit_start=" + newLimit : "";
					layer.msg('删除成功',{icon: 1});
					setTimeout(function(){
						if(domainAgentId.length == <?php echo count($domainList);?> && <?php echo intval($isLast);?> == 1) {
							window.location.href = document.location.href.replace(oldStr, newStr);
						} else {
							window.location.reload();
						}
					}, 500);
				} else if(data.flag == 2) {
					layer.msg(data.msg, {icon: 2});
 		 			$(':checkbox').prop('checked', false);
 		 			return false;
 	 			} else if(data.flag == 1) {
 	 				layer.msg('请先选择您要设置佣金比例的域名！', {icon: 2});
 	  				return false;
 				}
			}
		});
	}
	return false;
}

</script>
<?php $this->partial('seller/js');?>
<?php $this->partial('common/footer');?>
