<?php $this->partial("common/header"); ?>	
			<script type="text/javascript" src="/js/pickerDateRange/dateRange.js"></script>
			<link rel="stylesheet" type="text/css" href="/js/pickerDateRange/dateRange.css"/>
			<script type="text/javascript" src="/js/page.js"></script>
					<script type="text/javascript" src="/js/layer/layer.min.js"></script>
		<link rel="stylesheet" type="text/css" href="/js/layer/skin/layer.css">
		<div class="main_box">
<?php $this->partial("common/headernav"); ?>
			<div class="right main">
				<div class="com_tab_box clearfix">
<?php $this->partial("user/commonnav"); ?>
				</div>
				<div class="container">
				<form action='' id="orderForm">
					<div class="mt20">
						 <div class="ta_date" id="div_date_demo3">
                    <span class="date_title" id="date_demo3"></span>
                    <input type="hidden" value='<?php echo $this->request->getQuery('startDate');?>' name="startDate">
                    <input type="hidden" value='<?php echo $this->request->getQuery('endDate');?>' name="endDate">
                    <a class="opt_sel" id="input_trigger_demo3" href="#">
                        <i class="i_orderd"></i>
                    </a>
                </div>
						<select class="com_select w_100 ml20 dateForm" name="OrderType">
							<option value=''>全部</option>
							<?php foreach ($OrderType as $key=>$val){
								if($this->request->getQuery('OrderType')==$key){
									echo "<option value={$key} selected='selected'>{$val}</option>";
								}
								else{
								echo "<option value={$key}>{$val}</option>";
									}
							}?>
						</select>
						 <input type="hidden" value='<?php echo intval($this->request->getQuery('topic'))?>' name="topic">
						<input type="button" class="com_search_btn ml20" id="getcsv" value="导 出" />
					</div>
					</form>
					<div class="mt20">
						<table class="domain_table_center clearfix" width="100%">
							<colgroup>
								<col width="10%"/>
								<col width="12%"/>
								<col />
								<col width="10%"/>
								<col width="10%"/>
								<col width="15%"/>
								<col width="10%"/>
								<col width="13%"/>					
							</colgroup>
							<thead>
								<tr>
									<th>订单编号</th>
									<th class="center">创建时间</th>
									<th class="center">域名</th>
									<th>订单状态</th>
									<th>交易类型</th>
									<th class="center">成交价格</th>
									<th>佣金比例</th>
									<th class="center">佣金金额</th>
								</tr>
							</thead>
							<tbody>
							<?php if(!empty($data['list'])){
								$str='';
								foreach ($data['list'] as $val){
									$str.="<tr><td>{$val->OrderId}</td>";
									$str.="<td>{$val->CreateTime}</td>";
									$str.="<td>{$val->DomainName}</td>";
									$str.="<td>{$val->StatusCn}</td>";
									$str.="<td>{$val->TransTypeCn}</td>";
									$str.="<td>".round($val->Price, 2)."元</td>";
									$str .= "<td>".round($val->Percent, 2)."%</td>";
									$str.="<td>".round($val->commission,2)."元</td></tr>";

								}
								echo $str;
								
							}
							else{
								echo '<tr><td colspan="10" style=" text-align: center;">无查询结果</td></tr>';
							}
							?>
								
							</tbody>
						</table>
					</div>
					<div class="page_box clearfix">
					<div class="right">
<?php echo $data['page'];?>
					</div>
					</div>
				</div>
			</div>
		</div>
			<script type="text/javascript">
			var today = getDays(0);
			var lasr7Days=getDays(-7);
			var defaultStartDate='<?php echo $this->request->getQuery('startDate');?>'?'<?php echo $this->request->getQuery('startDate');?>':lasr7Days;
			var defaultendDate='<?php echo $this->request->getQuery('endDate');?>'?'<?php echo $this->request->getQuery('endDate');?>':today;
				var dateRange = new pickerDateRange('date_demo3', {
					aRecent7Days : 'aRecent7DaysDemo3', //最近7天
					isTodayValid : true,
					startDate : defaultStartDate,
					endDate : defaultendDate,
					//needCompare : true,
					//isSingleDay : true,
					//shortOpr : true,
					defaultText : ' 至 ',
					inputTrigger : 'input_trigger_demo3',
					theme : 'ta',
					success : function(obj) {
						$("#dCon_demo3").html('开始时间 : ' + obj.startDate + '<br/>结束时间 : ' + obj.endDate);
						$('input[name="startDate"]').val(obj.startDate);
						$('input[name="endDate"]').val(obj.endDate);
					}
				});
					function getDays(AddDayCount){

					var dd = new Date(); 
					dd.setDate(dd.getDate()+AddDayCount);//获取AddDayCount天后的日期 
					var y = dd.getFullYear(); 
					var m = (dd.getMonth()+1)<10?"0"+(dd.getMonth()+1):(dd.getMonth()+1);//获取当前月份的日期，不足10补0
					var d = dd.getDate()<10?"0"+dd.getDate():dd.getDate(); //获取当前几号，不足10补0
					return y+"-"+m+"-"+d; 
					}
					$(function(){

						$('.ta_btn_primary').click(function(){
							$('#orderForm').submit();
						});
						$('.dateForm').change(function(){
							$('#orderForm').submit();
						})
						 $("#getcsv").click(function(){
								var url='<?php echo $this->url->get('User/exportOrderDetail');?>';
								$('#orderForm').attr('action',url);
								$('#orderForm').submit();						
							});
                   });
				var url='<?php echo $this->url->get('User/orderDetail',array('topic'=>intval($this->request->getQuery('topic'))));?>';
				var left_url='<?php echo $this->url->get('User/finance');?>';
				navLight(url,left_url);
				$(".menu_list").find('li').removeClass('menu_curren');
			</script>
<?php $this->partial("common/footer"); ?>