<?php $this->partial("common/header"); ?>
<script type="text/javascript" src="/js/pickerDateRange/dateRange.js"></script>
		<script type="text/javascript" src="/js/layer/layer.min.js"></script>
		<link rel="stylesheet" type="text/css" href="/js/layer/skin/layer.css">
<link rel="stylesheet" type="text/css"
	href="/js/pickerDateRange/dateRange.css" />
<div class="main_box">
<?php $this->partial("common/headernav"); ?>
<div class="right main">
		<div class="main_title">
			<span>申请转出</span>
		</div>
		<div class="container">
			<table class="domain_details_list mt20" width="100%">
				<colgroup>
					<col width="23%" />
					<col width="23%" />
					<col />
				</colgroup>
				<tbody>
					<tr>
						<td>
							<div>
								<p>未结算金额</p>
								<span><?php echo sprintf("%.2f",$data['sucessMoney']);?></span>
							</div>
						</td>
						<td>
							<div>
								<p>账户余额</p>
								<span><?php echo sprintf("%.2f",$data['Money']);?></span>
							</div>
						</td>
						<td>
							<div class="noborder com_btn_box">
								<label>转出金额</label> <input type="text"
									onfocus="if(this.value != ''){ this.value = '';}" onblur="if(this.value == ''){ this.value = '最高可转出<?php echo sprintf("%.2f",$data['Money']);?>';}"
									class="w_150 ml5 mr10 com_input" name="price" style="color:#737e73" value='最高可转出<?php echo sprintf("%.2f",$data['Money']);?>'/> <input
									type="button" class="refer_btn" value="转    出"
									onclick="turn_out();" style="height: 28px;line-height: 28px;font-size: 15px;"/>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
			<form action='' id="turnoutForm">
				<div class="mt20 clearfix">
						 <div class="ta_date" id="div_date_demo3">
                    <span class="date_title" id="date_demo3"></span>
                    <input type="hidden" value='<?php echo $this->request->getQuery('startDate');?>' name="startDate">
                    <input type="hidden" value='<?php echo $this->request->getQuery('endDate');?>' name="endDate">
                    <a class="opt_sel" id="input_trigger_demo3" href="#">
                        <i class="i_orderd"></i>
                    </a>
                </div>
				</div>
			</form>
			<div class="mt20">
				<table class="domain_table clearfix" width="100%">
					<colgroup>
						<col />
						<col width="30%" />
						<col width="30%" />
					</colgroup>
					<thead>
						<tr>
							<th>转出时间</th>
							<th>转出金额</th>
							<th>状态</th>
						</tr>
					</thead>
					<tbody>
								<?php
								
                     if(! empty($data['list']))
								{
									$str = '';
									foreach($data['list'] as $val)
									{
										$str .= "<tr><td>{$val->CreateTime}</td>";
										$str .= "<td>".round($val->Money, 2)."元</td>";
										$str .= "<td>{$val->StatusCn}</td></tr>";
									}
									echo $str;
								}
								else{
									echo '<tr><td colspan="10" style=" text-align: center;">无查询结果</td></tr>';
								}
								?>
							</tbody>
				</table>
			</div>
		</div>
		<div class="page_box clearfix">
		<div class="right">
<?php echo $data['page'];?>
					</div>
					</div>
	</div>
</div>
<script type="text/javascript">
			var today = getDays(0);
			var lasr7Days=getDays(-7);
			var defaultStartDate='<?php echo $this->request->getQuery('startDate');?>'?'<?php echo $this->request->getQuery('startDate');?>':lasr7Days;
			var defaultendDate='<?php echo $this->request->getQuery('endDate');?>'?'<?php echo $this->request->getQuery('endDate');?>':today;
				var dateRange = new pickerDateRange('date_demo3', {
					aRecent7Days : 'aRecent7DaysDemo3', //最近7天
					isTodayValid : true,
					startDate : defaultStartDate,
					endDate : defaultendDate,
					//needCompare : true,
					//isSingleDay : true,
					//shortOpr : true,
					defaultText : ' 至 ',
					inputTrigger : 'input_trigger_demo3',
					theme : 'ta',
					success : function(obj) {
						$('input[name="startDate"]').val(obj.startDate);
						$('input[name="endDate"]').val(obj.endDate);
					}
				});
					function getDays(AddDayCount){

					var dd = new Date(); 
					dd.setDate(dd.getDate()+AddDayCount);//获取AddDayCount天后的日期 
					var y = dd.getFullYear(); 
					var m = (dd.getMonth()+1)<10?"0"+(dd.getMonth()+1):(dd.getMonth()+1);//获取当前月份的日期，不足10补0
					var d = dd.getDate()<10?"0"+dd.getDate():dd.getDate(); //获取当前几号，不足10补0
					return y+"-"+m+"-"+d; 
					}
			var url='<?php echo $this->url->get('User/turnOut');?>';
			var left_url='<?php echo $this->url->get('User/turnOut');?>';
			navLight(url,left_url);
			$(".menu_list").find('li').removeClass('menu_curren');
			$(function(){
				$('.ta_btn_primary').click(function(){
					$('#turnoutForm').submit();
				});
			})
			function turn_out(){
		        if(!check_price()){
			        return false;}
		        if(!confirm('确认转出?')){
		            return false;
		        }
		        var price =$('input[name="price"]').val();
		        $.ajax({
		            type: "POST",
		        url: "<?php echo $this->url->get('User/doTurnOut');?>",
		        data: {'price':price},
		        beforeSend : function(){
		       },
		                success: function(data){
		                     if(data.status){
		                       alert('转出成功!');
		                       setTimeout(function(){
		                               location.reload();
		                       },500);
		                        }
		                     else{
		                    	 alert('转出失败,请重试!');
		                         }        
		                },
		        error: function(){
		        alert("系统繁忙");
		        }
		              });
				}
			function check_price(){
				var max_price=<?php echo round($data['Money'],2);?>;
				var price =$('input[name="price"]').val();
		        if(!price||price==null||price==undefined){
		        	layer.msg('请输入金额!',{icon: 2});
			        return false;
			        }
		       //// price=parseFloat(price);
		       // alert(price);
		        if(isNaN(price)){
		        	layer.msg('请输入数字!',{icon: 2});
		        	$('input[name="price"]').val(null);
		        	return false;
			        }
		        if(price<0.01){
		        	layer.msg('数值要大于0.01',{icon: 2});
		        	$('input[name="price"]').val(null);
		        	return false;
			        }
		        if(price>max_price){
		        	layer.msg('金额超过余额！',{icon: 2});
			        $('input[name="price"]').val(null);
			        return false;
			        }
		        return true;
				}
			</script>

<?php $this->partial("common/footer"); ?>