
	<div id="form-content" class="modal hide fade in ie" style="display: none;">
		<div class="pop_main one">
			<div class="pop_hd">
				<a title="关闭" href="#" class="pop_close" data-dismiss="modal">x</a>
				<h3>推广设置</h3>
			</div>
			<div class="pop_bd">
				<p class="pop_tip">小贴士：域名商品具有唯一性和时效性，推广链接有可能在短时间内失效，<a href="<?php echo $this->url->get('agentguests/autoagentindex');?>">自动推</a>可以自动更换掉失效链接。</p>
				<div class="border_gray mt10 pb20">
					<ul class="tuiguang_list clearfix">
						<li class="w_100"><span class="theme">推广至：</span> </li>
						<li>
							<p><input type="radio" name="PlatformType" id="zhanshi" value='2'/><label for="zhanshi">我的展示页</label><i id="cusInfo"></i></p>
							<p><input type="radio" name="PlatformType" id="ziyou" value='1'/><label for="ziyou">我的网站</label> 
								<i id='siteInfo'></i>
							</p>
							<p><input type="radio" name="PlatformType" id="others" value='3'/><label for="others">其他平台（url链接）</label>
								<i id='otherInfo'></i>
							</p>
						</li>
					</ul>
				</div>
				<div class="pb20 border_gray stylechoose">
					<ul class="tuiguang_list  clearfix">
						<li class="w_100"><span class="theme mt10">推广位样式：</span> </li>
						<li class="tuiguang_choose">
							<p class="mt10"><input type="radio" name="StyleId" id="yangshi1" value='1'/><label for="yangshi1">样式1</label> </p>
							<img src="/images/yangshi1.jpg" class="mt10" width="130" height="134" />
						</li>
						<li>
							<p class="mt10"><input type="radio" name="StyleId" id="yangshi2" value='2' /><label for="yangshi2">样式2</label> </p>
							<img src="/images/yangshi2.jpg" class="mt10" width="130" height="134" />
						</li>
						<li>
							<p class="mt10"><input type="radio" name="StyleId" id="yangshi3" value='3' /><label for="yangshi3">样式3</label> </p>
							<img src="/images/yangshi3.jpg" class="mt10" width="130" height="134" />
						</li>
					</ul>
				</div>
				<div class="pb20 border_gray themechoose">
<div class="pb10 clearfix">
					<div class="left w_100 mt15" style="padding-left: 20px;">
						<span class="theme">推送至模板：</span>
					</div>
					<ul class="tuiguang_list left clearfix moban" style="width: 530px;">
					</ul>
				</div>
															<div class="com_note mt20 clearfix">
	                    <h3 class="com_note_tit">注意事项：</h3>
	                    <ul class="com_note_list mt15">
	                        <li>推广代码将自动更替到您展示页模板上的推广位，如果不希望自动更新，点击<a href="javascript:void(0)" class="modalnext" style="font-size: 14px;">手动添加</a>复制代码</li>
	                        <li>自定义模板请使用其他方式推广</li>
	                    </ul>
	                </div>
				</div>
			</div>
			<p class="center"><input type="checkbox" name="checkAgreement" value='1'>请勾选并同意<a href="<?php echo $this->url->get('faq/detail/53');?>">《域名联盟推广服务协议》</a></p>
			<div class="com_btn_box mb30 mt20 pintai">
            	<input type="button" value="" class="com_btn modalnext" />
            	<input type="button" value="关闭" class="com_btn" data-dismiss="modal" />
            </div>
           <div class="com_btn_box mb30 mt20 zhanshiye">
            	<input type="button" value="推送" class="com_btn complete" />
            	<input type="button" value="关闭" class="com_btn" data-dismiss="modal" />
            </div>
		</div>
		<div class="pop_main two">
			<div class="pop_hd">
				<a title="关闭" href="#" class="pop_close" data-dismiss="modal">x</a>
				<h3>获取代码</h3>
			</div>
			<div class="pop_bd border_gray">
				<div class="pop_top">预览</div>
				<div class="center mt10 mb20 pb20 adData" style="max-height: 300px;overflow-y: scroll;_height:expression((document.documentElement.clientHeight||document.body.clientHeight)<1000?'1000px':'');">
				</div> 
				<div class="hot"><p class="hot_tishi">Ctrl+V将代码粘贴到自己的站点，即可形成推广位。</p></div>
			</div>
			
			<div class="clipboard-tip"></div>
			<div class="com_btn_box mb30 mt20">
            	<input type="button" value="复制代码" class="com_btn copy"/>
            	<input type="button" class="com_search_btn ml10 modalback" value="上一步"/>
			</div>
		</div>
				<div class="pop_main three" style="display: none;">
			<div class="pop_hd">
				<a title="关闭" href="#" class="pop_close" data-dismiss="modal">x</a>
				<h3>获取代码</h3>
			</div>
			<div class="pop_bd border_gray">
				<div class="pop_top"></div>
				<div class="center mb20">
					 <textarea class="pop_area adData copy"></textarea>
				</div> 
			</div>
			
			<div class="com_btn_box mb30 mt20">
            	<input type="button" value="关 闭" class="com_btn" data-dismiss="modal"/>
            	<input type="button" class="com_search_btn ml10 modalback" value="上一步"/>
            </div>
		</div>
</div>
	<script type="text/javascript">
$(document).ready(function() {
	$(".tuiguang_list input[name=StyleId]").click(function(){
		$(this).parent().parent().addClass("tuiguang_choose").siblings().removeClass("tuiguang_choose");
	});
	$(document).on('click',".tuiguang_list input[name=StyleIds]",(function(){
		 var __this=$(this);
	     $.ajax({
	         type: "GET",
	     url: "<?php echo $this->url->get('Custompage/getTemplateBySid');?>",
	     data: {'styleid':__this.val()},
	     beforeSend : function(){
	    },
	             success: function(data){
		             if(data.flag){
			             creat_moban(data.data.style,data.data.data,__this.val());
		             }     
	             },
	     error: function(){
	     layer.msg("系统繁忙",{icon: 5});
	     }
	           });
	}));
	function creat_moban(style,data,style_id){
        var html='';
		for ( var k in style) {
			html+='<li';
			if(parseInt(style[k].StyleId)==parseInt(style_id)){
                var select=' class="tuiguang_choose"><p class="mt10"><input type="radio" id="muban1" name="StyleIds" value='+(parseInt(style[k].StyleId))+' checked/><select class="TemplateDId">';
                 select += '<option value="">--请选择--</option>';
						for ( var key in data) {
							select += '<option value='+data[key].TemplateDId+'>'+data[key].TemplateName+ '</option>';
						}
						
						select += '</select>';
				html+=select;
				}
			else{
				html+='><p class="mt10"><input type="radio" id="muban1" name="StyleIds" value='+(parseInt(style[k].StyleId))+' /><label for="muban'+style[k].StyleId+'">'+style[k].tempname+'</label>';
				//console.log(data.data.style[k].styleid+'--');
			}
			html += '</p><img src="/upload/images/template/system'+parseInt(style[k].StyleId)+'.jpg" class="mt10" width="130" height="116" /></li>';
			}
		$('.moban').html(html);   
		}
	$(document).on('click',".tuiguang_list img",(function(){
		 var __this=$(this);
		 if(parseInt($('input[name="PlatformType"]:checked ').val())==2){
	     $.ajax({
	         type: "GET",
	     url: "<?php echo $this->url->get('Custompage/getTemplateBySid');?>",
	     data: {'styleid':__this.parent().find('input[name=StyleIds]').val()},
	     beforeSend : function(){
	    },
	             success: function(data){
		             if(data.flag){
		            	 creat_moban(data.data.style,data.data.data,__this.parent().find('input[name=StyleIds]').val());              
		             }     
	             },
	     error: function(){
	     layer.msg("系统繁忙",{icon: 5});
	     }
	           });
		 }
		 else{
				__this.parent().addClass("tuiguang_choose").siblings().removeClass("tuiguang_choose");
				}
	     __this.parent().find('input[name=StyleIds]').prop("checked",true).siblings().prop("checked",false);
	     __this.parent().find('input[name=StyleId]').prop("checked",true).siblings().prop("checked",false);
	}));
	var AgentType=<?php echo $data['AgentType'];?>;
	$('.ids').prop('checked',false);
	$('.checkall').prop('checked',false);
//twitter bootstrap script
 $(".ids").click(function(){
		var option = $(".ids");
		$(this).is(':checked')?$(this).attr("checked", true):$(this).attr("checked", false);
		option.each(function(i){
			if(!this.checked){
				$(".checkall").prop("checked", false);
				return false;
			}else{
				$(".checkall").prop("checked", true);
			}
		});
 });
 $('.checkall').click(function(){
	 $(".ids").prop("checked", this.checked);
 });
 $(".btn-primary").click(function(){ 
	 var agentId=$(this).attr('tag');
	 modalInit(agentId);
 });
 function getId(){
     var agentId=[];  
     $('.ids').each(function(i) {
         if ($(this).is(':checked')) { 
        	 agentId.push($(this).val());  
         }
     }); 
     return agentId;
	 }
 $('.modalnext').click(function(){
	 var agentId=[];
	 agentId=$('.oneids').val().split(",");
	 var PlatformType=$('input[name="PlatformType"]:checked ').val();
	 var StyleId=$('input[name="StyleId"]:checked ').val();
	 var StyleIds=$('input[name="StyleIds"]:checked ').val();
	 var siteId=PlatformType==2?0:$('.site').val();
	 if(PlatformType==''||PlatformType==undefined||PlatformType==null){
		 layer.msg('请选择推广类型',{icon: 5});
		 return false;
		 }
	 if(PlatformType==1){
	 if(StyleId==''||StyleId==undefined||StyleId==null){
		 layer.msg('请选择样式',{icon: 5});
		 return false;
		 }
	 $('.one').append('<input class="oneStyleId" type="hidden" name="StyleId" value='+StyleId+' />');
	 }
	 else if(PlatformType==2){
		 if(StyleIds==''||StyleIds==undefined||StyleIds==null){
			 layer.msg('请选择模板',{icon: 5});
			 return false;
			 }
		 $('.one').append('<input class="oneStyleIds" type="hidden" name="StyleIds" value='+StyleId+' />');
		 }
	 if(PlatformType==1||PlatformType==3){
	 if(siteId==''||siteId==undefined||siteId==null){
		 if(PlatformType==1){
			 var msg='请选择一个网站';
			 }else{
				 msg='请选择一个平台';
			 }
		 layer.msg(msg,{icon: 5});
		 $('.site').css('border', '2px red solid');
		 return false;
		 }
	 $('.one').append('<input class="onesiteId" type="hidden" name="siteId" value='+siteId+' />');
	 }
	 if(!$('input[name="checkAgreement"]').prop("checked")){
		 layer.msg('请勾选并同意《域名联盟推广服务协议》',{icon: 5});
		 return false;
		 }
	 $('.one').append('<input class="oneAgentType" type="hidden" name="AgentType" value='+AgentType+' />');
	 $('.one').hide();
	 if(PlatformType==1){
		 reviewBySite(agentId,StyleId);
	 $('.two').show();
	 }
	 else if(PlatformType==3||PlatformType==2){
		 adByOther(agentId,StyleIds,siteId,PlatformType)
		 $('.three').show();
		 }
	 });
 function reviewBySite(agentId,StyleId){
	 $('.pop_top').html('预览');

                    
       			 var agentId=[];
    			 agentId=$('.oneids').val().split(",");
    			 var siteId=$('.site').val();
    			 var StyleId=$('input[name="StyleId"]:checked ').val();
    			 var PlatformType=$('input[name="PlatformType"]:checked ').val();
    		     $.ajax({
    		         type: "GET",
    		     url: "<?php echo $this->url->get('Agentguests/spreadAgent');?>",
    		     data: {'AgentId':agentId,'StyleId':StyleId,'AgentType':AgentType,'PlatformId':siteId,'PlatformType':PlatformType,'Agreement':1},
    		     beforeSend : function(){
    		    },
    		             success: function(data){
    		            	 $('.adData').html(data[0]); 
    		            	 copy(data[1]);
    		             },
    		     error: function(){
    		     layer.msg("系统繁忙",{icon: 5});
    		     }
    		           });

	 }
 function adByOther(agentId,StyleId,siteId,PlatformType){
     $.ajax({
         type: "POST",
     url: "<?php echo $this->url->get('Agentguests/spreadAgent');?>",
     data: {'AgentId':agentId,'StyleId':StyleId,'AgentType':AgentType,'PlatformId':siteId,'PlatformType':PlatformType,'Agreement':1},
     beforeSend : function(){
    },
             success: function(data){
                  if(data){
                    $('.adData').text(data); 
                    copy(data);
                 }        
             },
     error: function(){
     layer.msg("系统繁忙",{icon: 5});
     }
           });
	 }
	  $('.modalback').click(function(){
		  backclean();
	 $('.one').show();
	 $('.two').hide();
	 $('.three').hide();
	 });
 function backclean(){
	 $('.pop_top').html('');
	 $('.onesiteId').remove();
	 $('.oneStyleId').remove();
	 $('.oneAgentType').remove();
	 }
	 $('.modalrest').click(function(){
		 $('.site').remove();
		 $('.oneids').remove();
		 $('#reviewPic').html('');
		 });
			 function init(){
			 $('.one').show();
			 $('.two').hide();
			 $('.three').hide();
			 $('.site').html('');
			 $('#otherInfo').html('');
			 $('.oneids').remove();
			 $('.onesiteId').remove();
			 $('.oneStyleId').remove();
			 $('.oneStyleIds').remove();
			 $('.oneAgentType').remove();
			 $('#reviewPic').html('');
			 $('.clipboard-tip').html('');
			 //$('input[name="StyleId"]').attr("checked",false);
			 $('input[name="StyleId"]:eq(0)').prop("checked",true).siblings().prop("checked",false);
			 $('input[name="StyleIds"]:eq(0)').prop("checked",true).siblings().prop("checked",false);
			 $('input[name="PlatformType"]:eq(0)').prop("checked",true).siblings().prop("checked",false);
			 $('input[name="StyleId"]:eq(0)').parent().parent().addClass("tuiguang_choose").siblings().removeClass("tuiguang_choose");
			 $('input[name="StyleIds"]:eq(0)').parent().parent().addClass("tuiguang_choose").siblings().removeClass("tuiguang_choose");
			 $('.pop_top').html('');
			 $('input[name="checkAgreement"]').prop("checked",false);
			 }
		 function copy(data){
			    $(".copy").zclip({
					path: "/js/zclip/ZeroClipboard.swf",
					copy: function(){
					return data;
					},
					beforeCopy:function(){/* 按住鼠标时的操作 */
						$(this).css("color","orange");
					},
					afterCopy:function(){/* 复制成功后的操作 */
						$('.pop_top').html('<span class="success_top">代码复制成功</span>');
						//$(".copy-tips").fadeOut(3000);
			        }
				});
		 }
		 
		 $(".btn-primaryall").click(function(){
			 var agentId=getId();
			 if(agentId==''||agentId==undefined||agentId==null){
				 layer.msg('请选择',{icon: 5});
				 return false;
				 }
			 modalInit(agentId);
		 });
		 $(document).on('mousemove',".tuiguang_list img",(function(e){
			 $(this).siblings(".imagebig").remove();
				var xx = e.clientX;
				var yy = e.clientY; 
				var width = $(this).attr("width");
				var height = $(this).attr("height");
				var src = $(this).attr("src");
				var srcs = src.split("/");
				var newsrc = '';
				for (var i = 0 ; i < srcs.length ; i++) {
					if(i == (srcs.length-1)){
						newsrc +='big' + srcs[i];
					}else{
						newsrc += srcs[i] + "/";
					}
				}
				var bigImg = "<img class='imagebig' style='top:"+ (yy-100) +"px;left:"+ (xx + 10) +"px;' src="+ newsrc +" />";
				$(this).parent().append(bigImg);
			 }));
		 $(document).on('mouseout',".tuiguang_list img",(function(){ 
			 $(this).siblings(".imagebig").remove();
			 }));
		 $("#ziyou").click(function(){
			 cleanType();
			 $('.modalnext').val('生成代码');
			$('.stylechoose').show();
			$('.themechoose').hide();
			$('.pintai').show();
			$('.zhanshiye').hide();
		         $.ajax({
		     type: "POST",
		 url: "<?php echo $this->url->get('Platform/getSiteByType');?>",
		 data: {'PlatformType':1},
		 beforeSend : function(){
		},
		         success: function(data){
		             if(data){
		                 var str='<select class="com_select w_110 ml10 site" onchange="cancle_color(this)">';
		                 str += '<option value="">--网站名称--</option>';
								for ( var k in data) {
									str += '<option value='+data[k].PlatformId+'>'+data[k].Name+ '</option>';
								}
								
								str += '</select><a class="ml10" href="<?php echo $this->url->get('Platform/addSite');?>" target=_blank>新增网站+</a>';
		                 $("#siteInfo").html(str);
		             }        
		         },
		 error: function(){
		 layer.msg("系统繁忙",{icon: 5});
		 }
		       });
		 });
		 $("#zhanshi").click(function(){
			 cleanType();
			 $('.stylechoose').hide();
			 $('.themechoose').show();
				$('.pintai').hide();
				$('.zhanshiye').show();
			     $.ajax({
			         type: "GET",
			     url: "<?php echo $this->url->get('Custompage/getTemplateBySid');?>",
			     data: {},
			     beforeSend : function(){
			    },
			             success: function(data){
				                  if(data.flag){
					                  var html='';
					                  if(data.data.style==''||data.data.style==undefined||data.data.style==null){
						                 html='此处仅显示系统模板，如果您还没有生成系统模板，请先去<a target=_blank href='+'<?php echo $this->url->get('custompage/custompagestyle');?>'+' >生成系统模板</a>，或者使用<em style="color:red;">我的网站推广</em>选项生成推广位代码。';
					                  }else{
					                	  var i=0;
											for ( var k in data.data.style) {
												html += '<li><p class="mt10"><input type="radio" id="muban1" name="StyleIds" value='+(parseInt(data.data.style[k].StyleId))+' /><label for="muban'+data.data.style[k].StyleId+'">'+data.data.style[k].tempname+'</label> </p><img src="/upload/images/template/system'+data.data.style[k].StyleId+'.jpg" class="mt10" width="130" height="116" /></li>';
				i++;
												}
											$('#cusInfo').html('<a target=_blank class="ml10" href="<?php echo $this->url->get('custompage/custompagestyle');?>">新增展示页+</a>');
						                  }
					                  $('.moban').html(html);  
				             }
				              else{
				            	  layer.msg("系统繁忙",{icon: 5});

				                  }    
			             },
			     error: function(){
			     layer.msg("系统繁忙",{icon: 5});
			     }
			           });
		 });
			 $("#others").click(function(){
				 cleanType();
				 $('.modalnext').val('生成链接');
				 $('.stylechoose').hide();
				 $('.themechoose').hide();
					$('.pintai').show();
					$('.zhanshiye').hide();
		         $.ajax({
				     type: "POST",
				 url: "<?php echo $this->url->get('Platform/getSiteByType');?>",
				 data: {'PlatformType':3},
				 beforeSend : function(){
				},
				 success: function(data){
				             if(data){
				                 var str='<select class="com_select w_110 ml10 site" onchange="cancle_color(this)">';
				                 str += '<option value="">--选择平台--</option>';
										for ( var k in data) {
											str += '<option value='+data[k].PlatformId+'>'+data[k].Name+ '</option>';
										}
										str += '</select><a target=_blank class="ml10" href="<?php echo $this->url->get('Platform/otherList');?>">新增平台+</a>';
				                 $("#otherInfo").html(str);
				             }        
				         },
				 error: function(){
				 layer.msg("系统繁忙",{icon: 5});
				 }
				       });
			 });
			 function cleanType(){
				 $('#siteInfo').html('');
				 $("#otherInfo").html('');
				 $('#cusInfo').html('');
				 }
			 function modalInit(agentId){
				 init();
				 $('.one').append('<input class="oneids" type="hidden" name="id" value='+agentId+' />');
				 $('#zhanshi').trigger('click');
		         $('#form-content').modal({backdrop: 'static', keyboard: false}); 
				 }
			 $('.complete').click(function(){
				 var PlatformType=2;
				 var StyleIds=$('input[name="StyleIds"]:checked ').val();
				 var agentId=[];
				 var TemplateDId=$('.TemplateDId').val();
				 agentId=$('.oneids').val().split(",");
				 if(StyleIds==''||StyleIds==undefined||StyleIds==null){
					 layer.msg('请选择模板',{icon: 5});
					 return false;
					 }
				 if(TemplateDId==''||TemplateDId==undefined||TemplateDId==null){
					 layer.msg('请选择模板数据',{icon: 5});
					 return false;
					 }
				 if(!$('input[name="checkAgreement"]').prop("checked")){
					 layer.msg('请勾选并同意《域名联盟推广服务协议》',{icon: 5});
					 return false;
					 }
		         $.ajax({
				     type: "POST",
				 url: "<?php echo $this->url->get('Agentguests/spreadAgent');?>",
			     data: {'AgentId':agentId,'StyleId':StyleIds,'AgentType':AgentType,'PlatformId':TemplateDId,'PlatformType':PlatformType,'Agreement':1},
				 beforeSend : function(){
				},
				 success: function(data){
				             if(data){
				            	 var id=data[1];
				    	         $.ajax({
								     type: "GET",
								 url: "<?php echo $this->url->get('Custompage/autoAgentForUser');?>",
								 data: {'templateid':data[1],'codeid':data[0]},
								 beforeSend : function(){
								},
								 success: function(data){
								             if(data){
								            	 layer.confirm('推送成功', {icon: 1,title:'',
								            	    btn: ['查看展示页','继续推广'] //按钮
								            		}, function(){
								            			window.open("/custompage/dataview?id="+id);
								            		}, function(index){
								            			layer.close(index);
								            		});
								             }        
								         },
								 error: function(){
								 layer.msg("系统繁忙",{icon: 5});
								 }
								       });
				             }        
				         },
				 error: function(){
				 layer.msg("系统繁忙",{icon: 5});
				 }
				       });

				 })

});
function cancle_color(obj){
	if($(obj).val()!=''&&$(obj).val()!=undefined&&$(obj).val()!=null&&$(obj).val()!=0){
		$(obj).removeAttr("style");
	}else{
		$(obj).css('border', '2px red solid');
		}
					 }
</script>