				<div class="com_tab_box clearfix">
					<ul class="clearfix left">
						<li><a href="<?php echo $this->url->get('agentguests/domainagent');?>">推域名</a></li>
						<li>|<a href="<?php echo $this->url->get('agentguests/shopagent');?>">推店铺</a></li>
						<li>|<a href="<?php echo $this->url->get('agentguests/autoagentindex');?>">自动推</a></li>
					</ul>
					<a class="right mr20" style="color: #666f80;font-weight: 700;" href="<?php echo $this->url->get('faq/index', array('type'=>2));?>"><img src="../images/money.png" width="18" style="margin-right:5px;margin-top:-2px;"/>赚钱指南</a>
				</div>