<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="keywords" content="">
	<meta name="description" content="">
	
	<link rel="stylesheet" href="/css/style.css">

	<title>链接过期</title>


</head>
<body class="link-expire">
    
    <div class="tip-b">
	  <img class="tip-pic" src="/images/link-expire.jpg">
	  <div class="tip-text"><a href="/">域名联盟</a></div>
    </div>
	
</body>
</html>